- hosts: localhost
  roles: [sys, ec2, jenkins, build]
  vars:
    sys_ssh_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      your ssh key
      -----END RSA PRIVATE KEY-----

    sys_ssh_public_key: "ssh-rsa your ssh public key ubuntu@"

  tasks:
    - name: copy release scripts
      copy: src=/opt/packages/release dest=/opt/build/ owner=ubuntu group=ubuntu mode=0755

    - name: copy jenkins jobs
      copy: src=/opt/packages/jenkins dest=/var/lib/ owner=jenkins group=jenkins
      notify: restart-jenkins

    - name: clone project repo
      git: repo=git@bitbucket.org:demo/demo-project.git dest=/opt/build/depot/demo-project accept_hostkey=yes
      become_user: ubuntu

    - name: clone env repo
      git: repo=git@bitbucket.org:demo/demo-env-project.git dest=/opt/build/depot/demo-env-project accept_hostkey=yes
      become_user: ubuntu