- hosts: localhost
  roles: [sys, ec2, tomcat, nginx]
  vars:
    tomcat_java_opts: '-XX:+UseG1GC -Xms2300m -Xmx2300m -Xss256k -Djava.awt.headless=true'
    ec2_log_s3_bucket: demo-log
    ec2_cloudwatch_metrics: [java, linux]

  tasks:
    - name: deploy war
      copy: src=/opt/packages/demo-service.war dest=/var/lib/tomcat7/webapps/ROOT.war