language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle
script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
