- name: install supervisor
  apt: name=supervisor

- name: update /etc/init.d/supervisor
  copy: src=etc/init.d/supervisor.sh dest=/etc/init.d/supervisor owner=root group=root mode=0755

- name: create /opt/app
  file: path=/opt/app owner=root group=root mode=0777 state=directory

- name: create /opt/log/supervisor
  file: path=/opt/log/supervisor owner=root group=root mode=0755 state=directory

- name: update /var/log/supervisor
  file: path=/var/log/supervisor owner=root group=root mode=0755 state=directory

- name: update /etc/logrotate.d/supervisor
  copy: src=etc/logrotate.d/supervisor dest=/etc/logrotate.d/supervisor

- name: update /etc/supervisor/conf.d/program.conf
  template: src=etc/supervisor/conf.d/program.conf.j2 dest=/etc/supervisor/conf.d/program.conf
  notify: restart-supervisor

- name: enable supervisor service
  service: name=supervisor enabled=yes
